name: PHP Linting
on: push

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: PHP Lint 7.4
        uses: dbfx/github-phplint/7.4@master
      - name: PHP Lint 8.0
        uses: dbfx/github-phplint/8.0@master
